title: "Matt Beaudin"
logo: "assets/profile.jpeg"
description: >
  Seasoned IT professional with 18 years of experience across multiple sectors. For the past 6 years, I've been working in software teams providing log analysis and resolution for customer escalations. 
  <br/>
  Strong familiarity with principles and best practices of Privileged Access Management, Identity Access Management and security policies. Based in Québec, Canada.
  <br/>
  <a href="https://www.linkedin.com/in/mattbeaudin/">View my LinkedIn profile</a>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
